### ISSUE TITLE
Publish a new version to crates.io

### ISSUE THREAD

**Issue by myzhang1029** [plotters-rs/plotters-cairo#19]
Hi @38,
The current git version uses `cairo-rs == "^0.15.1"` but the one on `crates.io` still depends on `"^0.9.1"`. Would you mind publishing a new version to `crates.io`?

**Comment by facorread** [comment]
Hi @myzhang1029, the team welcomes contributions that help plotters keep up with the new features of cairo-rs. Would you like to consider setting up a pull request that ensures `plotters-cairo` builds and tests correctly on `cairo-rs == "^0.15.1"`? Your contribution would be much appreciated by the community.

**Comment by AaronErhardt** [comment]
I just did a new release: https://crates.io/crates/plotters-cairo
