### ISSUE TITLE
Publish version update on crates.io

### ISSUE THREAD

**Issue by MelonenBiber** [plotters-rs/plotters-cairo#29]
Hey, I wanted to ask whether someone could put the breaking version changes for **cairo-rs** to `0.17.X` on crates.io?
Currently in the git version **plotters-backend** is pulled from the **plotters-rs/plotters** git which clashes (for some reason) with the **plotters-rs** `0.3.4` release.

Thank you in advance!

**Comment by AaronErhardt** [comment]
Only @38 has the permission to do this. At least we have a GitHub organization to keep the project alive while some members are inactive but in the end, only @38 has the permission to do most things.

**Comment by AaronErhardt** [comment]
@sdroege I now have the permission to publish on crates.io, but I'm not sure if just publishing the version in this repo would be fine according to semver. The last version on crates.io is 0.3.2 and this repo has 0.3.3, but this only correct if bumping cairo from 0.15 to 0.17 isn't a breaking change.

**Comment by sdroege** [comment]
Yes that's not correct. This needs to become 0.4.0

**Comment by AaronErhardt** [comment]
Thanks, it's finally published now :tada:

**Comment by sdroege** [comment]
Yay, thanks for taking care of this :)

**Comment by baarkerlounger** [comment]
@AaronErhardt would you be willing to publish another crates.io version for the recent **cairo-rs** `0.18.x` bump?

**Comment by AaronErhardt** [comment]
@baarkerlounger done (as v0.5.0) 🚀
